### PR TITLE
Add comment syntax highlight

### PR DESCRIPTION
**Pull request by caioaao**

### CODE REVIEW

**Comment by Asalle** [comment]
damn, I haven't seen there is a pull request! thanks, I'll take a look!

**Comment by Asalle** [comment]
thank you so much for you contribution! I check it out and somehow not all comments are highlighted (see pic). Do you maybe have an idea why?

Screenshot from 2020-02-27 21-31-22

**Comment by caioaao** [comment]
I saw some issues like that, but couldn't solve them :/

**Comment by Asalle** [comment]
No worries, I think we can merge this one and then we'll think of some fix 🙂

**Pull request merged**
